services:
  db:
    image: postgres:17
    shm_size: 4g
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "./pg-db:/var/lib/postgres"

volumes:
  pg-db:
