import type { Metadata } from 'next'
import { PageContainer } from '@/components/layout/page-container'
import { BackLink } from '@/components/shared/back-link'
import { PageHeader } from '@/components/shared/page-header'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Proof of Transfer',
}

export default function TermsPage() {
  return (
    <PageContainer>
      <div className="mb-4">
        <BackLink href="/" label="Back to Claims" />
      </div>

      <PageHeader title="Terms of Service" />

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
        <p className="text-muted-foreground">Last updated: March 16, 2026</p>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">1. Acceptance</h2>
          <p>
            By using Proof of Transfer (&quot;the Service&quot;), you agree to these terms. If you
            do not agree, do not use the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">2. What the Service Does</h2>
          <p>
            Proof of Transfer allows users to create claims about on-chain token transfers and
            generate zero-knowledge proofs to verify those transfers without revealing wallet
            addresses. The Service fetches publicly available blockchain data from block explorer
            APIs.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">3. Not Financial or Legal Advice</h2>
          <p>
            The Service produces cryptographic proofs, not legal evidence. A verified proof means the
            math checks out — it does not constitute legal, financial, or compliance attestation of
            any kind. A verified proof does not verify the real-world identity of any party. Do not
            rely on proofs generated by this Service for regulatory, legal, or financial decisions.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">4. Experimental Technology</h2>
          <p>
            The Service uses experimental zero-knowledge proof technology (Noir circuits,
            Barretenberg WASM, UltraHonk). While we strive for correctness, we make no guarantees
            that the cryptographic implementations are free of bugs or vulnerabilities. Use at your
            own risk.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">5. User Responsibilities</h2>
          <ul className="list-disc space-y-1 pl-6">
            <li>You are responsible for the content of claims you create (claim messages are publicly visible)</li>
            <li>You must not use the Service for illegal activity, fraud, or sanctions evasion</li>
            <li>You must not abuse the Service (automated scraping, denial-of-service, etc.)</li>
            <li>You are responsible for securing your wallet and private keys</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">6. Blockchain Data</h2>
          <p>
            Transfer data is sourced from public blockchain APIs (e.g., Etherscan). We do not
            guarantee the completeness, accuracy, or timeliness of this data. The Service stores
            copies of publicly available transfer data for display and merkle tree construction.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">7. No Warranty</h2>
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
            PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, the Service and its operators shall not be liable
            for any indirect, incidental, special, consequential, or punitive damages, including but
            not limited to loss of funds, data, or profits arising from your use of the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">9. Open Source</h2>
          <p>
            The Service is open source under the MIT License. The source code is available on{' '}
            <a
              href="https://github.com/tarasnurko/transferproover"
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold underline hover:opacity-80"
            >
              GitHub
            </a>
            . You are free to inspect, modify, and self-host the software. These Terms apply only
            to this hosted instance, not to self-hosted deployments.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">10. Changes to Terms</h2>
          <p>
            We may update these terms at any time. Continued use of the Service after changes
            constitutes acceptance of the updated terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold uppercase">11. Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions
            shall continue in full force and effect.
          </p>
        </section>
      </div>
    </PageContainer>
  )
}
